// Code generated by protoc-gen-go. DO NOT EDIT manually.
// This is a pre-generated stub so the project compiles without protoc.
// Run `make proto` to regenerate from proto/manga.proto.

package proto

import (
	"context"
	"google.golang.org/grpc"
)

// ─── Request/Response types ────────────────────────────────────────────────

type GetMangaRequest struct{ Id string }
type SearchRequest struct {
	Query  string
	Status string
	Genre  string
	Page   int32
	Limit  int32
}
type UserStatsRequest struct{ UserId string }
type PingRequest struct{ Message string }

type MangaResponse struct {
	Id           string
	Title        string
	Author       string
	Status       string
	ChapterCount int32
	CoverUrl     string
	Rating       float64
	Description  string
	Genres       []string
}
type MangaListResponse struct {
	Manga []*MangaResponse
	Total int32
	Page  int32
}
type UserStatsResponse struct {
	UserId        string
	TotalManga    int32
	Reading       int32
	Completed     int32
	TotalChapters int32
	AverageRating float64
}
type PongResponse struct {
	Message  string
	ServerId string
}

// ─── Server interface ──────────────────────────────────────────────────────

type MangaServiceServer interface {
	GetManga(context.Context, *GetMangaRequest) (*MangaResponse, error)
	SearchManga(context.Context, *SearchRequest) (*MangaListResponse, error)
	GetUserStats(context.Context, *UserStatsRequest) (*UserStatsResponse, error)
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedMangaServiceServer()
}

type UnimplementedMangaServiceServer struct{}

func (UnimplementedMangaServiceServer) GetManga(context.Context, *GetMangaRequest) (*MangaResponse, error) {
	return nil, nil
}
func (UnimplementedMangaServiceServer) SearchManga(context.Context, *SearchRequest) (*MangaListResponse, error) {
	return nil, nil
}
func (UnimplementedMangaServiceServer) GetUserStats(context.Context, *UserStatsRequest) (*UserStatsResponse, error) {
	return nil, nil
}
func (UnimplementedMangaServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, nil
}
func (UnimplementedMangaServiceServer) mustEmbedUnimplementedMangaServiceServer() {}

// ─── Client interface ──────────────────────────────────────────────────────

type MangaServiceClient interface {
	GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*MangaResponse, error)
	SearchManga(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*MangaListResponse, error)
	GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type mangaServiceClient struct{ cc grpc.ClientConnInterface }

func NewMangaServiceClient(cc grpc.ClientConnInterface) MangaServiceClient {
	return &mangaServiceClient{cc}
}

func (c *mangaServiceClient) GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*MangaResponse, error) {
	out := &MangaResponse{}
	err := c.cc.Invoke(ctx, "/manga.MangaService/GetManga", in, out, opts...)
	return out, err
}
func (c *mangaServiceClient) SearchManga(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*MangaListResponse, error) {
	out := &MangaListResponse{}
	err := c.cc.Invoke(ctx, "/manga.MangaService/SearchManga", in, out, opts...)
	return out, err
}
func (c *mangaServiceClient) GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error) {
	out := &UserStatsResponse{}
	err := c.cc.Invoke(ctx, "/manga.MangaService/GetUserStats", in, out, opts...)
	return out, err
}
func (c *mangaServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := &PongResponse{}
	err := c.cc.Invoke(ctx, "/manga.MangaService/Ping", in, out, opts...)
	return out, err
}

// ─── Server registration ───────────────────────────────────────────────────

var _MangaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manga.MangaService",
	HandlerType: (*MangaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetManga", Handler: _MangaService_GetManga_Handler},
		{MethodName: "SearchManga", Handler: _MangaService_SearchManga_Handler},
		{MethodName: "GetUserStats", Handler: _MangaService_GetUserStats_Handler},
		{MethodName: "Ping", Handler: _MangaService_Ping_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manga.proto",
}

func RegisterMangaServiceServer(s grpc.ServiceRegistrar, srv MangaServiceServer) {
	s.RegisterService(&_MangaService_serviceDesc, srv)
}

func _MangaService_GetManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := &GetMangaRequest{}
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/manga.MangaService/GetManga"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetManga(ctx, req.(*GetMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_SearchManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := &SearchRequest{}
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).SearchManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/manga.MangaService/SearchManga"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).SearchManga(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := &UserStatsRequest{}
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/manga.MangaService/GetUserStats"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetUserStats(ctx, req.(*UserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := &PingRequest{}
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/manga.MangaService/Ping"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}
